using BlockLogic.TrickleSystem.Backers;
using NPoco;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlockLogic.TrickleSystem
{
    [TableName("Backers")]
    [PrimaryKey("ID")]
    public class Backer
    { 
        public int ID { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.None)] // use this line infront of properties if Entity tries to insert null into the table, entity thinks the property is an identity which will be auto generated by sql server
        public int Funding { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public double TotalMoney { get; set; }
        public string BTCPrivateKey{ get; set; }

        public Backer(int ID, int Funding, string Name, string Email, float TotalMoney)
        {
            this.ID = ID;
            this.Funding = Funding;
            this.Name = Name;
            this.Email = Email;
            this.TotalMoney = TotalMoney;
        }
        public Backer()
        {
            ID = 0;
            Funding = 0;
            Name = "";
            Email = "";
            TotalMoney = new double();
        }

        public void AddFundAccount(int Funding)
        {
            this.Funding = Funding;
        }

        public int GetFundingAccount()
        {
            return Funding;
        }

        public void AddEmailAddress(string Email)
        {
            this.Email = Email;
        }
        public string GetEmailAddress()
        {
            return Email;
        }
    }
}
